# Generated by Django 2.1.4 on 2020-04-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historicaldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.TextField(blank=True)),
                ('openingprice', models.TextField(blank=True)),
            ],
        ),
    ]
