# Generated by Django 2.1.4 on 2020-04-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='closingprice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='volume',
            field=models.TextField(blank=True),
        ),
    ]
